name:                haskell-mqtt
version:             0.1.0.0
github:              "githubuser/haskell-mqtt"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-mqtt#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring == 0.10.12.0
- split == 0.2.3.4
- text == 1.2.4.1
- utf8-string == 1.0.2

library:
  source-dirs: src

executables:
  haskell-mqtt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-mqtt

tests:
  haskell-mqtt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-mqtt
